### ISSUE TITLE
Multiple downloads in from a single execution

### ISSUE THREAD

**Issue by stewartadam** [SteamRE/DepotDownloader#100]
Supporting multiple downloads from a single execution would be very helpful because currently, a 2FA prompt is generated for each download. Each execution also bump the login count and Steams limits logins to ~10 logins/30m.

Supporting reading a series of CLI arguments from a file (one per line) and re-using the same login session to grab multiple sets of files would prevent the repeated 2FA prompts and login limit.

**Comment by rossengeorgiev** [comment]
Does `-remember-password` not work?

**Comment by azuisleet** [comment]
Multiple downloads are probably not possible unless someone is willing to submit a patch.

You can run the program in series using -remember-password as suggested.

**Comment by shakeyourbunny** [comment]
The 2FA login (and the login itself) will be cached for subsequents calls, if you use -remember-password.

Caveat: During the the whole download process you must not open oder reopen the Steam client, either the CLI or the graphical one, as this will invalidate your login.

This is by design of the authentication process of Steam.
