### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by ProblemJuice** [SteamRE/DepotDownloader#165]
I try opening the game but it keeps sending me to the original and not the depot

**Comment by VoiDeD** [comment]
Please provide more detail for what issue you're having.

Note however that it doesn't sound like your issue is something we likely can directly help with. Running older versions of applications downloaded with depotdownloader is outside the scope of what the tool does - but we can maybe offer some guidance if it happens to be a game that we familiar with (source engine games, mostly, see #162  as an example).

**Comment by mmvanheusden** [comment]
This is normal for some games.
The solution is to replace the new version of the game with the downloaded older one and running Steam in offline mode.

**Comment by azuisleet** [comment]
This sounds unrelated to DepotDownloader itself. This tool does not facilitate the actual process of launching games. Steam has its own mechanism for file checking. If you have any other issues with the tool, feel free to open a new issue.
