### ISSUE TITLE
doesn't connect to steam

### ISSUE THREAD

**Issue by Atlas5714** [SteamRE/DepotDownloader#268]
Whenever i try to downgrade Stardew Valley to 1.4 or any other version, and I enter my correct username and password, it refuses to work

heres what it looks like from my end.

<img width="665" alt="2021-10-15 (5)" src="https://user-images.githubusercontent.com/92595707/137520155-1a95603a-d55e-4bb9-bc02-9401377d38aa.png">

**Comment by Ryah** [comment]
To add more info, they're using my batch script which uses DepotDownloader. I tried helping them but it seems like the problem is their connection to steam through DepotDownloader.
https://github.com/Ryah/SDV-Downgrader/

The command being run is `DepotDownloader.exe -app 413150 -depot 413151 -manifest 2373680906867811602 -username %user_name% -password %user_password% -dir SDV1.4`

And since they didn't post the screenshot showing -debug, here it is. ![](https://cdn.discordapp.com/attachments/898599650343395399/898600737314054165/2021-10-15_2.png)

**Comment by azuisleet** [comment]
Most likely you have a firewall of some sort that is preventing access to the Steam servers. If you have any more information, feel free to re-open this issue.
