### ISSUE TITLE
Unable to Connect to Steam- "Unable to decrypt incoming packet: NetFilterEncryption was unable to decrypt packet: HMAC from server did not match computed HMAC"

### ISSUE THREAD

**Issue by darkborn202** [SteamRE/DepotDownloader#272]
So, after attempting to roll back Skyrim Special Edition after this stupid update, I've run into this problem:

![image](https://user-images.githubusercontent.com/71355535/141367434-f7afbfc2-d8dd-4720-95e1-20c85bcfb9b2.png)

I know it has to do with HMAC- the HMAC doesn't match, hence it can't decrypt and read the packet, so eventually it times out. ...That's pretty much it. While I do have a sneaking suspicion it's user idiocy, I'm apparently too dumb to figure out what exactly I'm doing wrong to do such a result.

I basically followed the instructions on this video: https://www.youtube.com/watch?v=A0zyuaDVOY8&ab_channel=AiCave
Any help would be appreciated. Thanks for reading this!

**Comment by yaakov-h** [comment]
What version of DepotDownloader are you running on, and on what version of .NET?

**Comment by azuisleet** [comment]
Pleas ensure you're using DepotDownloader 2.4.5 as it includes fixes for .NET 6.0 (now generally available) and CDN authentication.

https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.5 

This is an expected SteamKit error with .NET 6.0 and was fixed in https://github.com/SteamRE/SteamKit/pull/1006 and DepotDownloader was packaged with 2.4.0-Alpha.3 in 2.4.4 https://github.com/SteamRE/DepotDownloader/commit/bd1314da2ee65295b1f4ba6f8edc3a2ed639d9c4

**Comment by azuisleet** [comment]
If you still have issues, feel free to open a new issue.
