### ISSUE TITLE
Help to update Steam game

### ISSUE THREAD

**Issue by EmreDemircan** [SteamRE/DepotDownloader#274]
Hello,
I am trying to do an update game. For example, It's Apex Legends APPID: 1172470
When the update is required (on the steam client ), I want to update the game from DepotDownloader.

First, I am closing the steam client from the status bar (right-click exit)
I tried to code something like that;
`DepotDownloader.exe -app 1172470 -username mysteamaccount -password mysteampassword -dir "E:\Steam\steamapps\common\Apex Legends" -validate`
It downloads, then I tried to edit app manifest file (Steam\steamapps\appmanifest_1172470.acf) StateFlags to 4, BytesToDownload to 0, BytesToStage to 0 [(steam appmanifest)](https://steamcommunity.com/sharedfiles/filedetails/?id=885555151)

But when I open again the steam client, It still says the game requires an update.
Need help, thank you!

**Comment by gregstein** [comment]
You are missing the -depot and -manifest. For example:

`DepotDownloader.exe -app 1172470 -depot 1172471 -manifest 8265030777718421006 -username mysteamaccount -password mysteampassword -dir "E:\Steam\steamapps\common\Apex Legends" -validate`

![Screenshot_1](https://user-images.githubusercontent.com/16618729/142783893-487991af-7948-423c-8b80-727af1bc0aa9.jpg)

You must go here https://steamdb.info/app/1172470/patchnotes/ then click any of the Patch Title (in your case 2 November 2021 patch) then you'll find more than one Depot. So that means you will need to create more than one commands using each depot and manifest as explained above.

**Comment by EmreDemircan** [comment]
> You are missing the -depot and -manifest. For example:
> 
> `DepotDownloader.exe -app 1172470 -depot 1172471 -manifest 8265030777718421006 -username mysteamaccount -password mysteampassword -dir "E:\Steam\steamapps\common\Apex Legends" -validate`
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/16618729/142783893-487991af-7948-423c-8b80-727af1bc0aa9.jpg)
> 
> You must go here https://steamdb.info/app/1172470/patchnotes/ then click any of the Patch Title (in your case 2 November 2021 patch) then you'll find more than one Depot. So that means you will need to create more than one commands using each depot and manifest as explained above.

Thanks, How will I know the depot and manifest id dynamically? I need to make it automatically. And does depotdownloader update the game manifest file automatically after downloading depot?

**Comment by gregstein** [comment]
I feel like answering you in a short video for better understanding 

https://streamable.com/sfqwj4

**Comment by EmreDemircan** [comment]
> I feel like answering you in a short video for better understanding
> 
> https://streamable.com/sfqwj4
> 
> On second thought I might create an app to automate the whole process.

Thank you very much! I would expect the DepotDownloader to do this automatically (update as steam client). Thank you again!

**Comment by gregstein** [comment]
Anytime brother!
