### ISSUE TITLE
How do you compile this? Is there a compiled version?

### ISSUE THREAD

**Issue by Herotroll** [SteamRE/DepotDownloader#51]
Hi. I'm new to all this and I want to download TF2 Version 0.
I don't know how to compile this at all.
Also, I would greatly appreciate if someone could send me a compiled .exe version.
Thank you all.

**Comment by psychonic** [comment]
There is a precomiled version in the Releases section. There is no exe since it is compiled as a framework-dependent .NET Core project.

`dotnet DepotDownloader.dll <args>`

That said, TF2 "Version 0" does not exist on the Steam3 / SteamPipe content servers. Steam2 was in use back then, and is long gone.
